clc
clear
close all

%Type in the following list the algorithms you want to compare. Check
%documentation for available algorithms.
algorithms = {'Runnals','Salmond','Williams'};

%Type it the test to use. Check documentation for available tests.
test = 'random';

%Check documentation for parameter meaning
params = struct('Nh',10,...
                'Nr',5,...
                'd',1,...
                'alpha',10,... %In general setting it to Nh/4 gives nice visual results
                'beta',0.09,...
                'delta',0,...
                'pruneGMComps',0,...
                'pruningMethod',1,...
                'pruningThresh',0.01,...
                'rho',0.9544,...
                'lambda',0.0,...
                'maxiter',100,...
                'cost_measure','W2',...
                'initMethodCTD','greedy',...
                'algoWest',0,...
                'gammaWest',Inf,...
                'EMSamples',1000,... %In general 150*Nh*n gives nice approximations
                'I',5,...
                'nEMIter',20,...
                'initMethodEM','greedy',...
                'nKMeansSteps',100,...
                'opt',1,...
                'sk',0.005,...
                'nOptSteps',100,...
                'optWeights',1,...
                'showResults',1,...
                'nPoints',300);

[fullMixture, gmr_vector, gmr_times] = GaussianMixtureReduction(algorithms,test,params);


